# Generated by Django 5.2 on 2025-04-12 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionEpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.now)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.asignacionepp')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('talla', models.CharField(choices=[('N/A', 'N/A'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46'), (48, '48'), (50, '50'), (52, '52'), (54, '54'), (56, '56'), (58, '58')], default='N/A', max_length=4)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionepp',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.producto'),
        ),
        migrations.AddField(
            model_name='asignacionepp',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.trabajador'),
        ),
    ]
