# Generated by Django 5.2 on 2025-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('N/A', 'N/A'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58')], default='N/A', max_length=4),
        ),
    ]
