# Generated by Django 5.2 on 2025-04-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0002_alter_producto_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
